name: jcgpractice
favicon: null
layout_spectrum: 0.88013
typography_spectrum: 0.34785
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050503'
    - '#9b9524'
    - '#0f6615'
    - '#655b12'
    - '#e0d66e'
  brandStrength: 0.0709866404067725
  lightness: 0.906555104535073
  saturation: 0.9342267841566354
  rhythmicContrast: 0.5
purpose: []
